# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokscoop" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "0a53882823ba76726594410e74d79198bafbc048fdab64187b8f0ca9cf14ca15"
      url "https://github.com/cobayo/tokscoop/releases/download/v#{version}/tokscoop_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "86640084905d716c8f2ea801f603f0267c2bc8ee8d75eaaec314ab94b5523e92"
      url "https://github.com/cobayo/tokscoop/releases/download/v#{version}/tokscoop_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5939cf838316facd8f55df37a6ad9888465452e3b19d3b1aa1116ff0f16db45d"
      url "https://github.com/cobayo/tokscoop/releases/download/v#{version}/tokscoop_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "33b510a55227018f1b0128e1a9530e6015055b00a0547c0f5b5819c12218f4e1"
      url "https://github.com/cobayo/tokscoop/releases/download/v#{version}/tokscoop_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tokscoop"
  desc "Local proxy that records token usage of Claude Code, Codex and other AI CLIs"
  homepage "https://github.com/cobayo/tokscoop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokscoop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tokscoop"]
    end
  end

  # No zap stanza required
end
