# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokscope" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "f90f924bacd6b9be976ef4cdcd7592047244541aa68be9538e47e7cbbd009526"
      url "https://github.com/cobayo/tokscoop/releases/download/v#{version}/tokscope_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d31a805ccdb0bd90927df292b1c7afdb5122e94bdeb3243807c8dd19b1e8844c"
      url "https://github.com/cobayo/tokscoop/releases/download/v#{version}/tokscope_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1fb083d3b76dd5891e444f8bac5a29ccd940160b548e93332773fd5ebc0bfd3d"
      url "https://github.com/cobayo/tokscoop/releases/download/v#{version}/tokscope_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9253fd40a49844536e2623a24cedc77dbcb96376e3d29d52b0edd115be16b49e"
      url "https://github.com/cobayo/tokscoop/releases/download/v#{version}/tokscope_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tokscope"
  desc "Local proxy that records token usage of Claude Code, Codex and other AI CLIs"
  homepage "https://github.com/cobayo/tokscoop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokscope"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tokscope"]
    end
  end

  # No zap stanza required
end
